#!/usr/bin/env python3
"""Pre-review checks for Ingénieur Ch5 (Validation). See tools/review/lib.py.

Ch5 owns every measured figure of the Ingénieur, so its sources are results/, never STATE.md or the
roadmap. Each figure is recomputed from the file the chapter drew it from:
  - lead-in: results/exp2_raw/*.jsonl (per-trial SoC temperature and throttle word);
  - 5.1 latency experiment: results/exp2.csv (the CSV of record), results/exp2_raw/*.jsonl
    (preemption outcomes, class matrix, the golden-set trigger), results/exp2_raw/meta.json (warm-up),
    results/exp2_analysis.md (core-0 frame budget), results/wake_real_voice.json (keyword false
    rejects on the author's takes);
  - 5.2 keyword-spotter evaluation: results/wake_training.json (rates, the "roc" grid, the interval);
  - 5.3 acoustic-robustness experiment: results/exp3_pi.csv, results/exp3_pi_analysis.md (tests, error
    analysis), results/exp3_pi_parity.csv, results/exp3_pi_preds/soc.log; the Master's
    table16_asr_speaker_sensitivity.md for the one sentence that cites it;
  - 5.4 formation-control experiment: results/exp4.csv, per trial, with the ANOVA and Tukey HSD redone
    by scipy;
  - 5.5 summary: results/requirements_summary.md (the verdict counts).

Beyond the numbers, it checks what the drafting brief fixed: the three generated tables are \\input
and nothing is retyped; the fixed verdicts keep their words (missed / not demonstrated / re-baseline,
not a pass); the collision sentence keeps Ch1's locked phrasing; Ch4's parameters (the 0.35 m
collision distance, the 0.80 m clamp distance, the 64-pass clamp) are referenced, not restated; the
Master's author-voice WER is cited without its number.
"""

import json
import math
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from lib import INGENIEUR, REPO, RESULTS, THESIS, Review, csv_rows, md_table, outline_check  # noqa: E402

import numpy as np  # noqa: E402
from scipy import stats  # noqa: E402

r = Review("ingenieur_ch5", "ingenieur", INGENIEUR[4], [*INGENIEUR[:4], *INGENIEUR[5:]])
r.common()
text = r.ch.text

outline_check(r, 4, {"Exp-2 (the latency experiment)": r"latency experiment",
                     "the keyword-spotter evaluation": r"keyword-spotter evaluation",
                     "Exp-3 (the acoustic-robustness experiment)": r"acoustic-robustness",
                     "Exp-4 (the formation-control experiment)": r"formation-control",
                     "a closing summary of every requirement": r"summary against the requirements"})


def jsonl(path: Path) -> list[dict]:
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def fnum(s: str) -> float:
    return float(s.replace(",", "").replace("{,}", ""))


# -- Tables are \input, never retyped ------------------------------------------------------------
for table, label in (("exp2_latency_budget", "tab:latency-budget"), ("table20_end_to_end", "tab:end-to-end"),
                     ("requirements_summary", "tab:requirements-summary")):
    r.expect("tables", f"\\input{{generated/{table}}}" in text,
             f"`{label}` is \\input from thesis/generated/{table}.tex, not retyped")
    gen = (THESIS / "generated" / f"{table}.tex").read_text(encoding="utf-8")
    r.expect("tables", f"\\label{{{label}}}" in gen, f"thesis/generated/{table}.tex carries \\label{{{label}}}")
r.expect("tables", "\\begin{tabular" not in text and "\\begin{tabularx" not in text,
         "no tabular typed in the chapter itself")
fig = re.search(r"\\includegraphics(?:\[[^]]*\])?\{([^}]*)\}", text)
r.expect("figure", fig is not None and (THESIS / fig.group(1)).resolve().is_file(),
         f"fig:keyword-curve includes `{fig.group(1) if fig else '?'}`, which exists (generated by eval/plots.py)")

# -- Lead-in: thermal state and records -----------------------------------------------------------
raw = {c: jsonl(RESULTS / "exp2_raw" / f"{c}.jsonl") for c in ("loaded", "branch_b", "idle")}
temps = [t["soc"]["temp"] for rows in raw.values() for t in rows]
r.number("stayed\nbetween 50.5 and", min(temps), "min SoC temperature at trial start, exp2_raw")
r.number("between 50.5 and 77.9~$^{\\circ}$C", max(temps), "max SoC temperature at trial start, exp2_raw", nth=1)
r.number("clear on all 360 trials", len(temps), "trials in exp2_raw (80 loaded + 200 parse + 80 idle)")
r.text_claim("claim", "clear on all 360 trials", all(t["soc"]["throttled"] == "0x0" for rows in raw.values() for t in rows),
             "throttle word 0x0 on every exp2_raw trial")
r.text_claim("claim", "logged the same two quantities\nevery 30~s",
             len({l[:8] for l in (RESULTS / "exp3_pi_preds/soc.log").read_text().splitlines()}) > 1,
             "soc.log is a temperature/throttle log (30 s cadence: see its timestamps)")
r.text_claim("claim", "single-command rerun that\nSection~\\ref{sec:engineering-requirements} requires is not provided",
             "bench.py --experiment 2" in (REPO / "run_all.sh").read_text() and
             "nothing to do" in (REPO / "eval/bench.py").read_text(),
             "run_all.sh still drives exp2-4 through bench.py, which without --dry-run does nothing -- "
             "if run_all.sh is fixed, this sentence can say the whole chapter reruns with one command", warn=True)

# -- 5.1 Latency experiment -------------------------------------------------------------------------
E = {(x["measure"], x["condition"]): x for x in csv_rows(RESULTS / "exp2.csv")}


def g(measure: str, cond: str, col: str = "p95") -> float:
    return float(E[(measure, cond)][col])


meta = json.loads((RESULTS / "exp2_raw/meta.json").read_text())
r.number("200 golden-set utterances in clean audio", len(raw["branch_b"]), "exp2_raw/branch_b items")
r.number("author's 40 recorded keyword takes", len({t["take"] for t in raw["idle"]}), "distinct takes")
r.number("20 per class", sum(1 for t in raw["idle"] if t["class"] == "swarm_hold" and t["pass"] == 0), "hold takes, one pass")
r.number("for 80\ntrials per condition", len(raw["idle"]), "idle trials")
r.number("preceded by 300~s", meta["warmup_s"], "meta.json warmup_s")
r.number("the processor was at 73.0", meta["soc_after_warmup"]["temp"], "meta.json soc_after_warmup")
r.number("whose p95 is under 1~ms", 1.0, "bound", tol=math.inf)
r.expect("claim", g("validate_fsm", "branch_b") < 1, f"validation row p95 {g('validate_fsm', 'branch_b')} ms < 1 ms")

r.number("keyword offset is 545~ms idle", g("a_offset", "idle"), "exp2.csv a_offset idle p95")
r.number("545~ms idle and 547~ms loaded, against 150", g("a_offset", "loaded"), "a_offset loaded p95", nth=1)
r.number("account for 540~ms at p95 in both", g("a_algorithmic", "idle"), "a_algorithmic idle p95")
r.expect("claim", g("a_algorithmic", "idle") == g("a_algorithmic", "loaded"), "spotter share equal idle and loaded")
r.number("account for 6~ms idle and 18", g("a_system", "idle"), "a_system idle p95")
r.number("6~ms idle and 18~ms loaded", g("a_system", "loaded"), "a_system loaded p95", nth=1)
r.number("before it (6 of 78 idle", 6, "idle detections before offset")
r.number("earliest\n$-$234.7~ms", 234.7, "idle earliest before offset")
r.number("4 of 78 loaded", 4, "loaded detections before offset")
r.number("earliest $-$234.0~ms", 234.0, "loaded earliest before offset")
r.number("raised the reflex path's p95 by 2~ms", round(g("a_offset", "loaded")) - round(g("a_offset", "idle")),
         "547 - 545, as the table rounds them")
fb = (RESULTS / "exp2_analysis.md").read_text()
frames = {m.group(1): m for m in re.finditer(
    r"- (\w+): (\d+) frames, compute p50 ([\d.]+) ms, p99 ([\d.]+) ms, max ([\d.]+) ms; over the 80 ms period: (\d+)", fb)}
r.text_claim("claim", "no frame in any condition took longer than the 80~ms",
             len(frames) == 3 and all(m.group(6) == "0" for m in frames.values()), "0 frames over 80 ms in all 3 phases")
r.number("computation was 14.2~ms", float(frames["loaded"].group(3)), "exp2_analysis.md loaded p50")
r.number("22.9~ms at p99", float(frames["loaded"].group(4)), "loaded p99")
r.number("45.5~ms at most", float(frames["loaded"].group(5)), "loaded max")
r.number("longest taking 74.2~ms", float(frames["branch_b"].group(5)), "branch_b max frame")
r.number("1{,}265~ms idle and 1{,}266", g("a_onset", "idle"), "a_onset idle p95")
r.number("1{,}265~ms idle and 1{,}266~ms loaded", g("a_onset", "loaded"), "a_onset loaded p95", nth=1)

loaded_events = [e for t in raw["loaded"] for e in t["events"]]
r.number("Of the 80 loaded trials, 78", len(raw["loaded"]), "loaded trials")
r.number("Of the 80 loaded trials, 78 produced", sum(1 for t in raw["loaded"] if t["events"]), "loaded trials with a detection", nth=1)
r.text_claim("claim", "every one of the 78 found a parse-path decode in progress",
             all(e["in_flight"] and e["aborted"] for e in loaded_events), "every loaded event in flight and aborted")
r.text_claim("claim", "No\ncancelled decode completed despite",
             "finished anyway (the abort lost the race): 0" in fb, "exp2_analysis.md: finished anyway 0")
for cond in ("idle", "loaded"):
    rows = raw[cond]
    fired = lambda cls, intent: sum(1 for t in rows if t["class"] == cls and any(e["intent"] == intent for e in t["events"]))  # noqa: E731
    r.text_claim("claim", "the 40\n\\emph{swarm abort} takes all fired", fired("swarm_abort", "abort") == 40,
                 f"{cond}: abort takes firing abort = {fired('swarm_abort', 'abort')}")
    r.text_claim("claim", "38 of the 40 \\emph{swarm hold} takes", fired("swarm_hold", "hover") == 38,
                 f"{cond}: hold takes firing hover = {fired('swarm_hold', 'hover')}")
    r.text_claim("claim", "No take fired the other\nclass", fired("swarm_hold", "abort") + fired("swarm_abort", "hover") == 0,
                 f"{cond}: cross-triggers = {fired('swarm_hold', 'abort') + fired('swarm_abort', 'hover')}")
    missed = {t["take"] for t in rows if not t["events"]}
    r.text_claim("claim", "The two misses are one take", len(missed) == 1, f"{cond}: missed takes {sorted(missed)}")
golden_hits = [(b["id"], b["branch_a_events"], json.loads(b["gold"])["intent"]) for b in raw["branch_b"] if b["branch_a_events"]]
r.text_claim("claim", "the reflex path fired once, a \\texttt{hover} during an utterance commanding a landing",
             len(golden_hits) == 1 and golden_hits[0][1] == ["hover"] and golden_hits[0][2] == "land",
             f"golden-set reflex triggers: {golden_hits}")
wt = json.loads((RESULTS / "wake_training.json").read_text())
r.text_claim("claim", "The spotter scored the\nsame recordings without a false accept",
             wt["golden"]["total"] == 0 if "total" in wt["golden"] else "0" in json.dumps(wt["golden"]),
             f"wake_training.json golden: {json.dumps(wt['golden'])[:120]}")

r.number("slot\nidle, is 1{,}195~ms at p95", g("recovery", "loaded"), "recovery p95")
r.number("within 6~ms of the trigger", g("abort_return", "loaded"), "abort_return p95", tol=0.5, note="x.5 in exp2.csv; the \\input table prints it half-to-even, and the prose follows the table")
r.number("recovery time, whose\nmedian is 601", g("recovery", "loaded", "p50"), "recovery p50")
r.number("maximum of 1{,}505~ms exceed", float(E[("recovery", "loaded")]["max"]), "recovery max")
r.number("10 of the 78 loaded recoveries exceed 1{,}000~ms", 10, "loaded recoveries > 1000 ms")

r.number("speech is 3{,}122~ms over", g("e2e_t0", "branch_b"), "e2e_t0 p95", tol=0.5, note="x.5 in exp2.csv; the \\input table prints it half-to-even, and the prose follows the table")
r.number("over 226 segments", float(E[("e2e_t0", "branch_b")]["n"]), "n")
r.number("a shortfall of 622~ms", g("e2e_t0", "branch_b") - 2500, "e2e p95 - 2500", tol=0.5, note="x.5 in exp2.csv; the \\input table prints it half-to-even, and the prose follows the table")
r.number("622~ms (25\\%)", 100 * (g("e2e_t0", "branch_b") / 2500 - 1), "e2e p95 / 2500 - 1", nth=1)
r.number("included, the p95 is 3{,}602", g("e2e_speech_end", "branch_b"), "e2e_speech_end p95", tol=0.5, note="x.5 in exp2.csv; the \\input table prints it half-to-even, and the prose follows the table")
r.number("recognition reaches 1{,}449", g("stt", "branch_b"), "stt p95")
r.number("reaches 751~ms against 250", g("prefill", "branch_b"), "prefill p95")
r.number("decode, at 915~ms", g("decode", "branch_b"), "decode p95")
r.number("re-baselined to the measured 3{,}122", g("e2e_t0", "branch_b"), "e2e_t0 p95", tol=0.5, note="x.5 in exp2.csv; the \\input table prints it half-to-even, and the prose follows the table")
r.number("configuration misses by 622", g("e2e_t0", "branch_b") - 2500, "e2e p95 - 2500", tol=0.5, note="x.5 in exp2.csv; the \\input table prints it half-to-even, and the prose follows the table")
r.text_claim("verdict", "This is a\nre-baseline, not a pass", True, "re-baseline stated as a re-baseline")
r.number("endpointing wait (480~ms", g("vad_wait", "branch_b"), "vad_wait p95")
stages = ("vad_wait", "stt", "prefill", "decode", "validate_fsm")
r.text_claim("claim", "Three meet their\nallowance", sum(E[(s, "branch_b")]["verdict"] == "MEETS" for s in stages) == 3,
             f"stage verdicts: { {s: E[(s, 'branch_b')]['verdict'] for s in stages} }")
r.number("worker, 73~ms at p95", g("queue", "branch_b"), "queue p95")
r.number("language-model server, 8~ms at p95", g("http", "branch_b"), "request overhead p95")

wr = {x["class"]: x for x in json.loads((RESULTS / "wake_real_voice.json").read_text())["rows"]}
wpk = json.loads((RESULTS / "wake_real_voice.json").read_text())["peaks"]
h, a = wr["swarm_hold"], wr["swarm_abort"]
r.number("give one miss in 20 for the hold", h["missed"], "hold missed")
r.number("one miss in 20 for the hold", h["n"], "hold n", nth=1)
r.number("rate of 0.050 with", h["frr"], "hold FRR")
r.number("interval of [0.001, 0.249]", h["frr_ci95"][0], "hold CI low")
r.number("[0.001, 0.249]", h["frr_ci95"][1], "hold CI high", nth=1)
r.number("none in 20 for the abort", a["n"], "abort n")
r.number("0.000 with [0.000, 0.168]", a["frr"], "abort FRR")
r.number("0.000 with [0.000, 0.168]", a["frr_ci95"][1], "abort CI high", nth=2)
r.number("upper bound\nstays at 0.168", a["frr_ci95"][1], "zero-miss upper bound at n = 20")
r.text_claim("verdict", "The criterion is therefore not\ndemonstrated",
             h["frr_ci95"][1] > 0.10 and a["frr_ci95"][1] > 0.10, "both upper bounds above 0.10")
r.number("peaked at a score of 0.9977", wpk[h["missed_takes"][0]]["swarm_hold"], "missed take's peak")
r.text_claim("claim", "it is the take missed on both replays on the board",
             {t["take"] for t in raw["idle"] if not t["events"]} == set(h["missed_takes"]),
             f"board's missed take {sorted({t['take'] for t in raw['idle'] if not t['events']})} = {h['missed_takes']}")

# -- 5.2 Keyword-spotter evaluation -----------------------------------------------------------------
roc = sorted(wt["roc"]["test"], key=lambda p: p["threshold"])
op = next(p for p in roc if p["threshold"] == wt["threshold"])
r.number("operating threshold of 0.999 selected", wt["threshold"], "wake_training.json threshold")
flat = [p for p in roc if abs(p["fa_per_hour_ambient"] - op["fa_per_hour_ambient"]) < 1e-9]
r.number("survives\nevery threshold from 0.88", min(p["threshold"] for p in flat), "lowest threshold at the operating FA")
r.text_claim("claim", "within that range, raising the threshold only adds false rejects",
             all(roc[i + 1]["frr"][c] >= roc[i]["frr"][c] for i in range(len(roc) - 1) for c in ("swarm_hold", "swarm_abort")
                 if roc[i] in flat), "FRR non-decreasing across the flat range")
tp = wt["test"]["positives"]
r.number("the hold class misses 0.027", tp["frr"]["swarm_hold"], "test FRR hold")
r.number("of its 300 test takes", tp["n"]["swarm_hold"], "test n hold")
r.number("the abort class 0.007", tp["frr"]["swarm_abort"], "test FRR abort")
r.text_claim("claim", "One hold take fired the abort class", tp["cross_trigger"]["swarm_hold"]["swarm_abort"] == 1
             and tp["cross_trigger"]["swarm_abort"]["swarm_hold"] == 0, f"cross-triggers {tp['cross_trigger']}")
vp = wt["val"]["positives"]
r.number("the rates are 0.027 and 0.000", vp["frr"]["swarm_hold"], "val FRR hold")
r.number("0.027 and 0.000 over 150", vp["frr"]["swarm_abort"], "val FRR abort", nth=1)
r.number("over 150 takes per class", vp["n"]["swarm_hold"], "val n")
wmd = (RESULTS / "wake_training.md").read_text()
d95 = {m.group(1): m.group(2) for m in re.finditer(r"\| test \| `(\w+)` \|.*?\| (\d+) ms \|\n", wmd)}
r.number("is 188~ms at p95 for the hold", float(d95["swarm_hold"]), "wake_training.md test hold delay p95")
r.number("131~ms for\nthe abort class", float(d95["swarm_abort"]), "test abort delay p95")
r.number("it is 550~ms and 430", h["delay_p95_ms"], "author hold delay p95")
r.number("550~ms and 430~ms", a["delay_p95_ms"], "author abort delay p95", nth=1)
amb = wt["test"]["ambient"]
r.number("speech, 0.429~h long", amb["hours"], "test ambient hours")
r.text_claim("claim", "produced one\nfalse accept, on the abort head", amb["events"] == {"swarm_hold": 0, "swarm_abort": 1},
             f"test ambient events {amb['events']}")
r.number("That is 2.33 per hour", amb["per_hour"], "per hour")
r.number("Poisson interval of [0.06,", amb["per_hour_ci95"][0], "CI low")
r.number("12.98], against a budget", amb["per_hour_ci95"][1], "CI high")
r.text_claim("verdict", "the criterion is not\ndemonstrated", amb["per_hour_ci95"][0] < 1 < amb["per_hour_ci95"][1],
             "interval straddles 1/h")
va = wt["val"]["ambient"]
r.number("The validation stream, 0.167~h", va["hours"], "val ambient hours")
r.number("interval of [0.00, 22.13]", va["per_hour_ci95"][1], "val CI high", nth=1)
r.number("produced none in 0.304~h", wt["golden"]["hours"], "golden hours")
nm = wt["test"]["near_miss"]
r.number("produced 34 false accepts in 0.100", nm["total"], "near-miss events")
r.number("in 0.100~h, 31 of them", nm["hours"], "near-miss hours")
r.number("31 of them on the hold head", nm["events"]["swarm_hold"], "near-miss hold")
r.number("the 300 synthetic test takes of", tp["n"]["swarm_abort"], "caption n")
r.number("0.429~h of ambient speech, summed", amb["hours"], "caption hours")
r.number("selection grid from 0.05", roc[0]["threshold"], "caption grid start")

# -- 5.3 Acoustic-robustness experiment -------------------------------------------------------------
X = {x["condition"]: x for x in csv_rows(RESULTS / "exp3_pi.csv")}
c, t10, t5 = X["clean"], X["10"], X["5"]
r.number("in clean audio is 0.690", float(c["crr"]), "clean CRR")
r.number("interval of [0.625, 0.750]", float(c["crr_lo"]), "clean CRR lo")
r.number("[0.625, 0.750], against", float(c["crr_hi"]), "clean CRR hi", nth=1)
r.number("reaches an \\gls{em} of 0.935", float(c["em"]), "EM on reference text")
r.number("costs\n0.245 [0.185, 0.310]", float(c["em_minus_crr"]), "EM - CRR clean")
r.number("0.245 [0.185, 0.310] of", float(c["em_minus_crr_lo"]), "lo", nth=1)
r.number("0.245 [0.185, 0.310] of", float(c["em_minus_crr_hi"]), "hi", nth=2)
an = (RESULTS / "exp3_pi_analysis.md").read_text()
cause_hdr = re.search(r"\| Condition \| failed \| parser wrong.*?\n\|[-: |]+\n((?:\|.*\n)+)", an)
cause = {row.split("|")[1].strip(): [int(v) for v in row.split("|")[2:9]] for row in cause_hdr.group(1).splitlines()}
cc = cause["clean"]  # failed, parser-on-text, no segment, split, perfect+wrong, ASR intent, ASR slot
r.number("Each of the 62 failed", cc[0], "clean failures")
r.number("splits account for 22", cc[3], "split cause, clean")
r.number("23 of the 200 utterances were split", int(c["n_split"]), "clean splits")
r.number("all 23 failed", int(re.search(r"\| clean \| \d+ \| \d+ \| \d+ \| (\d+)/\d+ \|", an).group(1)), "split items failed")
r.number("wrong accounts for 23", cc[6], "ASR right intent wrong slot")
r.number("changed the intent for 5", cc[5], "ASR wrong intent")
r.number("reference text for 12", cc[1], "parser wrong on text")
r.text_claim("claim", "no\nutterance was transcribed perfectly and then misparsed", cc[4] == 0, f"perfect + wrong = {cc[4]}")
r.number("the clean \\gls{crr} is 0.730", float(c["crr_last_segment"]), "last-segment CRR")
r.number("at 11.5\\% of the\ngolden set", 100 * int(c["n_split"]) / int(c["n"]), "split rate", places=1)
r.number("at 10~dB the \\gls{crr} is 0.590", float(t10["crr"]), "10 dB CRR", nth=1)
r.number("0.590\n[0.520, 0.660]", float(t10["crr_lo"]), "lo", nth=1)
r.number("[0.520, 0.660], against", float(t10["crr_hi"]), "hi", nth=1)
r.number("rises from 0.245 clean", float(c["em_minus_crr"]), "EM-CRR clean")
r.number("to 0.345 [0.280, 0.410]", float(t10["em_minus_crr"]), "EM-CRR 10")
r.number("0.345 [0.280, 0.410] at", float(t10["em_minus_crr_hi"]), "hi", nth=2)
r.number("and 0.450 [0.380, 0.520] at 5", float(t5["em_minus_crr"]), "EM-CRR 5")
r.number("from 23.3\\% clean", 100 * float(c["wer"]), "WER clean", places=1)
r.number("to 28.8\\% at 10~dB", 100 * float(t10["wer"]), "WER 10", places=1)
r.number("and 36.0\\% at 5~dB", 100 * float(t5["wer"]), "WER 5", places=1)
c10 = cause["10 dB"]
r.number("rise from 5 to 19", c10[5], "ASR wrong intent 10 dB", nth=1)
r.number("from 23 to 30", c10[6], "ASR slot 10 dB", nth=1)
r.number("errors stay at 12", c10[1], "parser on text 10 dB")
r.number("splits fall from 22 to 20", c10[3], "split cause 10 dB", nth=1)
env = re.search(r"CRR >= 0.65.*?\| (\d+) dB \| none", an)
r.number("down to 15~dB on the point", float(env.group(1)), "exp3_pi_analysis.md envelope")
r.number("(0.650 exactly)", float(X["15"]["crr"]), "15 dB CRR")
t16 = (RESULTS / "table16_asr_speaker_sensitivity.md").read_text()
prompted = float(re.search(r"author's commands: [\d.]+% → ([\d.]+)%", t16).group(1))
r.text_claim("claim", "within a\nfraction of a point", abs(100 * float(c["wer"]) - prompted) < 1,
             f"clean WER {100 * float(c['wer']):.1f}% vs Master's prompted {prompted}% (table16)")
r.text_claim("ownership", "speaker-sensitivity experiment of the \\emph{M\\'emoire de\nMaster}",
             f"{prompted}" not in text and "23.0" not in text and "23.1" not in text,
             "the Master's author-voice WER is cited without its number")

fm = re.search(r"F\(4, 995\) = ([\d.]+), p = (\d[\d.]*(?:e[+-]?\d+)?)", an)
r.number("$F(4, 995) = 6.03$", float(fm.group(1)), "exp3_pi_analysis.md F", nth=2)
r.text_claim("claim", "$p = 8.6 \\times 10^{-5}$", math.isclose(float(fm.group(2)), 8.6e-5, rel_tol=0.01), f"p = {fm.group(2)}")
tukey = {(row[1].strip(), row[2].strip()): float(row[4]) for row in
         (l.split("|") for l in an.splitlines()) if len(row) == 6 and row[1].strip() in ("clean", "20 dB", "15 dB", "10 dB")
         and "dB" in row[2] and re.match(r"\s*[\d.e-]+\s*$", row[4])}
sig_t = {k for k, p in tukey.items() if p < 0.05}
r.text_claim("claim", "Tukey's honestly-significant-difference comparison~\\cite{kramer1956} separates 5~dB from clean, 20\nand 15~dB, and no other pair",
             sig_t == {("clean", "5 dB"), ("20 dB", "5 dB"), ("15 dB", "5 dB")}, f"Tukey p < 0.05: {sorted(sig_t)}")
r.number("grouped into 12\ncommand patterns", 12, "template patterns")
qm = re.search(r"Q = ([\d.]+), df = (\d+), p = (\d[\d.]*(?:e[+-]?\d+)?)", an)
r.number("($Q = 61.05$", float(qm.group(1)), "Cochran's Q")
r.number("4 degrees of freedom", float(qm.group(2)), "df")
r.text_claim("claim", "$p = 1.7 \\times 10^{-12}$", math.isclose(float(qm.group(3)), 1.7e-12, rel_tol=0.01), f"p = {qm.group(3)}")
mc = {(row[1].strip(), row[2].strip()): (float(row[6]), row[7].strip()) for row in
      (l.split("|") for l in an.splitlines()) if len(row) == 9 and row[7].strip() in ("yes", "no")}
sig_m = {k for k, (_, s) in mc.items() if s == "yes"}
r.text_claim("claim", "separates clean from 10 and 5~dB,\nand 20 and 15~dB from 5~dB",
             sig_m == {("clean", "10 dB"), ("clean", "5 dB"), ("20 dB", "5 dB"), ("15 dB", "5 dB")}, f"McNemar significant: {sorted(sig_m)}")
r.number("$\\alpha = 0.0050$, separates", 0.05 / 10, "Bonferroni over 10 pairs")
r.number("10~dB with 5~dB is\nnot significant, at $p = 0.0051$ (exact binomial $p = 0.0046$)", mc[("10 dB", "5 dB")][0], "McNemar 10 vs 5", nth=2)
r.number("10~dB with 5~dB is\nnot significant, at $p = 0.0051$ (exact binomial $p = 0.0046$)", 0.0046, "exact McNemar 10 vs 5", nth=3)
r.number("20~dB against 10~dB, at $p = 0.0053$ (exact binomial $p = 0.0046$)", mc[("20 dB", "10 dB")][0], "McNemar 20 vs 10", nth=2)
r.number("20~dB against 10~dB, at $p = 0.0053$ (exact binomial $p = 0.0046$)", 0.0046, "exact McNemar 20 vs 10", nth=3)

sf = {k: float(x["safe_failure_rate"]) for k, x in X.items() if k != "text"}
r.number("It is 0.032 in clean audio", sf["clean"], "clean safe-failure rate")
r.number("(2 of 62\nfailures)", float(c["n_safe"]), "clean safe failures")
r.number("between 0.014 and 0.039", min(sf.values()), "min over SNR")
r.number("0.014 and 0.039 at every", max(sf.values()), "max over SNR", nth=1)
r.number("grows from 62 clean to 103", float(t5["n_failed"]), "5 dB failures", nth=1)
safe_n = [int(x["n_safe"]) for k, x in X.items() if k != "text"]
r.number("safe failures stay between one and four", min(safe_n), "min safe count")
r.number("between one and four", max(safe_n), "max safe count", nth=1)
r.text_claim("verdict", "The criterion is missed\nat every level", max(sf.values()) < 0.70, "all below 0.70")
ab = csv_rows(RESULTS / "nfr9_nfr18_abstention.csv")
pooled = sum(int(x["safe_failures"]) for x in ab) / sum(int(x["errors"]) for x in ab)
r.number("measured on text input, 0.053", pooled, "Master's pooled safe-failure rate (ADR-0006 baseline)")
r.number("condition of this experiment has 13 failures and no safe", 13, "reference text failures")
r.text_claim("claim", "Recognition errors therefore do not make the failures\nless safe than the parser's own; neither input comes near the bound",
             max(sf.values()) < pooled, f"max {max(sf.values()):.3f} < {pooled:.4f}")

par = {x["condition"]: x for x in csv_rows(RESULTS / "exp3_pi_parity.csv")}
r.text_claim("claim", "none of the 200 raw outputs differs", par["text"]["raw_differs"] == "0" and par["text"]["n"] == "200",
             "text condition raw_differs 0")
tdiff = [int(x["transcript_differs"]) for k, x in par.items() if k != "text"]
r.number("Between two and six transcripts differ", min(tdiff), "min transcript differences")
r.number("two and six transcripts", max(tdiff), "max", nth=1)
r.text_claim("claim", "They change the outcome of two utterances at 10~dB, one in each\ndirection",
             par["10"]["flips_to_correct"] == "1" and par["10"]["flips_to_wrong"] == "1", "10 dB flips +1/-1")
r.text_claim("claim", "and of two at 5~dB, both towards failure", par["5"]["flips_to_wrong"] == "2"
             and par["5"]["flips_to_correct"] == "0", "5 dB flips 0/-2")
r.number("5~dB \\gls{crr} is 0.485 on the board", float(par["5"]["crr_candidate"]), "Pi 5 dB CRR", nth=1)
r.number("against 0.495 on the workstation", float(par["5"]["crr_reference"]), "workstation 5 dB CRR")
r.number("rises from 2{,}869~ms clean", float(c["e2e_p95_ms"]), "stage-sum p95 clean")
r.number("2{,}977~ms at 5~dB", float(t5["e2e_p95_ms"]), "stage-sum p95 5 dB")
r.number("an increase of 108~ms", round(float(t5["e2e_p95_ms"])) - round(float(c["e2e_p95_ms"])), "2977 - 2869")
r.number("recogniser running on four unpinned threads", 4, "unpinned threads")
r.text_claim("claim", "is a\nstage sum, not an end-to-end latency", True, "Table 20's last column named a stage sum")
log = (RESULTS / "exp3_pi_preds/soc.log").read_text().splitlines()
lt = [float(re.search(r"temp=([\d.]+)", l).group(1)) for l in log]
r.number("stayed between 54.3", min(lt), "soc.log min")
r.number("and 80.1~$^{\\circ}$C over the run", max(lt), "soc.log max")
first_flag = next(l.split()[0] for l in log if "0x80000" in l)
r.text_claim("claim", "set from 17:45", first_flag.startswith("17:45"), f"first flagged sample {first_flag}")

# -- 5.4 Formation-control experiment ---------------------------------------------------------------
F = csv_rows(RESULTS / "exp4.csv")
shapes = ("circle", "line", "wedge")
by = {s: [x for x in F if x["shape"] == s] for s in shapes}
r.number("circle of radius 5~m", 5, "circle radius")
r.number("and the wedge at 2~m spacing", 2, "formation spacing")
r.number("spacing, 50 trials each", len(by["wedge"]), "trials per shape")
r.number("for 150 trials of 60~s", len(F), "trials")
r.text_claim("claim", "the trial's index multiplied by 42",
             all(int(x["seed"]) == int(x["trial"]) * 42 for x in F), "seed = trial x 42 on every row")
r.text_claim("ownership", "Collisions and clamp interventions are counted as\nSection~\\ref{sec:swarm-controller} defines them",
             "0.35~m" not in text and "0.80~m" not in text and "64" not in text,
             "Ch4's collision distance, clamp distance and pass limit are referenced, not restated")
r.text_claim("verdict", "zero collisions were observed across all 150 trials,\nbacked by a hard geometric separation clamp at the integrator",
             sum(int(x["collisions"]) for x in F) == 0, "0 collisions, Ch1's locked phrasing")
r.number("the clamp made\n432 interventions", sum(int(x["clamp_activations"]) for x in F), "clamp interventions")
r.number("150 in the circle trials", sum(int(x["clamp_activations"]) for x in by["circle"]), "circle")
r.number("141 in the line", sum(int(x["clamp_activations"]) for x in by["line"]), "line")
r.number("and 141 in the wedge", sum(int(x["clamp_activations"]) for x in by["wedge"]), "wedge")
ca = [int(x["clamp_activations"]) for x in F]
r.number("between none and\n14 in a single trial", max(ca), "max per trial")
r.number("with 6 trials needing none", ca.count(0), "trials with none")
r.number("0.800~m, is the clamp distance", min(float(x["min_pair_distance"]) for x in F), "closest approach")
r.number("needed in 144 of the 150", len(F) - ca.count(0), "trials with an intervention")
fa = [float(x["formation_accuracy"]) for x in F]
r.number("formation accuracy is 1.000 in every", min(fa), "min FA")
r.text_claim("claim", "an analysis\nof variance on it has no variance", max(fa) == min(fa), "FA constant")
conv = {s: [float(x["convergence_seconds"]) for x in by[s]] for s in shapes}
r.text_claim("claim", "Every trial\nconverged", all(x["converged"] == "1" for x in F), "all converged")
r.number("the slowest after 4.32~s", max(max(v) for v in conv.values()), "slowest convergence")
r.text_claim("claim", "more than 55~s of the trial after convergence", 60 - max(max(v) for v in conv.values()) > 55, "60 - 4.32")
fe = {s: [float(x["final_mean_error"]) for x in by[s]] for s in shapes}
r.number("slot is 0.29~m in the circle", np.mean(fe["circle"]), "final slot error circle")
r.number("0.13~m in the line", np.mean(fe["line"]), "line")
r.number("and 0.07~m in the\nwedge", np.mean(fe["wedge"]), "wedge")
r.text_claim("claim", "varies by less than 3~mm", max(max(v) - min(v) for v in fe.values()) < 0.003,
             f"spread {max(max(v) - min(v) for v in fe.values()) * 1000:.1f} mm")
for s, anchor in (("circle", "Its median is\n4.06~s"), ("line", "3.26~s for the line"), ("wedge", "2.30~s for the wedge")):
    r.number(anchor, float(np.median(conv[s])), f"{s} median convergence")
iqr = {m.group(1): (float(m.group(2)), float(m.group(3)), float(m.group(4))) for m in re.finditer(
    r"\| (circle|line|wedge) \|.*?\| ([\d.]+) \[([\d.]+), ([\d.]+)\] \|", (RESULTS / "exp4_formation.md").read_text())}
for s_, (lo_a, hi_a) in (("circle", ("range 4.00--4.08", "4.00--4.08~s)")), ("line", ("(3.21--3.32", "3.21--3.32~s)")),
                         ("wedge", ("(2.21--2.38", "2.21--2.38~s)"))):
    r.number(lo_a, iqr[s_][1], f"{s_} IQR low, exp4_formation.md")
    r.number(hi_a, iqr[s_][2], f"{s_} IQR high, exp4_formation.md", nth=1)
anova = stats.f_oneway(*(conv[s] for s in shapes))
r.number("$F(2, 147) = 3500.7$", anova.statistic, "scipy f_oneway", nth=2)
r.text_claim("claim", "$p = 1.0 \\times 10^{-124}$", math.isclose(anova.pvalue, 1.0e-124, rel_tol=0.1), f"p = {anova.pvalue:.3g}")
tk = stats.tukey_hsd(*(conv[s] for s in shapes))
ci = tk.confidence_interval(0.95)
r.number("the circle takes 0.795~s", tk.statistic[0, 1], "Tukey circle - line")
r.number("(95\\% interval [0.745, 0.845])", ci.low[0, 1], "lo", nth=1)
r.number("[0.745, 0.845])", ci.high[0, 1], "hi", nth=1)
r.number("and 1.755~s longer", tk.statistic[0, 2], "circle - wedge")
r.number("([1.705, 1.805])", ci.low[0, 2], "lo")
r.number("the line\n0.960~s longer", tk.statistic[1, 2], "line - wedge")
r.text_claim("claim", "each at $p < 10^{-13}$", all(tk.pvalue[i, j] < 1e-13 for i, j in ((0, 1), (0, 2), (1, 2))),
             f"Tukey p: {[float(tk.pvalue[i, j]) for i, j in ((0, 1), (0, 2), (1, 2))]}")

# -- 5.5 Summary against the requirements -----------------------------------------------------------
rows = md_table(RESULTS / "requirements_summary.md", "Criterion")
verdicts = [x["Verdict"] for x in rows]
count = {v: verdicts.count(v) for v in dict.fromkeys(verdicts)}  # table order: set() made the report vary per run
r.number("Of the\nseventeen criteria", len(rows), "rows of the summary table")
r.number("seven are met", count.get("Met", 0), "Met")
r.number("five are missed", count.get("Missed", 0), "Missed")
r.number("two are not demonstrated", count.get("Not demonstrated", 0), "Not demonstrated")
r.number("Two more have not\nbeen run", count.get("Not yet run", 0), "Not yet run")
r.text_claim("claim", "The last, the live demonstration,\nis planned for the defence",
             count.get("Planned for the defence", 0) == 1, f"verdicts: {count}")
missed = [x["Criterion"] for x in rows if x["Verdict"] == "Missed"]
summary = text[text.index("\\section{Summary against the requirements}"):]
for crit in missed:
    r.expect("verdict", re.search(r"\s+".join(map(re.escape, crit.split())) + r"\s+is\s+missed", summary, flags=re.I) is not None,
             f"5.5 names `{crit}` as missed with a cause")

# -- Wording fixed by the brief -----------------------------------------------------------------------
for crit in ("Reflex latency", "End-to-end latency", "Preemption recovery", "Clean-audio recognition", "Recognition in noise"):
    sec = re.search(rf"\\paragraph\{{{re.escape(crit)}\.\}}\s*The criterion is (\w+)", text)
    r.expect("verdict", sec is None or sec.group(1) == "missed",
             f"`{crit}` paragraph opens `The criterion is {sec.group(1) if sec else '(no paragraph -- see 5.5)'}`")
r.expect("verdict", not re.search(r"(?:end-to-end latency|2\{,\}500~ms requirement)\s+(?:is|was)\s+(?:met|passed)", text, flags=re.I)
         and not re.search(r"\bmeets\s+the\s+2\{,\}500", text),
         "no sentence calls end-to-end latency, or the 2,500 ms requirement, met or passed")
r.expect("verdict", "guarantee" not in text.lower(), "no 'guarantee' anywhere (Ch1's locked collision phrasing)")

r.manual.append("### What only a reader can judge\n\n"
                "- Whether each located cause is the measurement's, or an interpretation that belongs to Ch6.\n"
                "- Whether 5.1's server-poll explanation for preemption recovery is supported (no results/ file "
                "states the once-per-second check; it comes from the llama-server configuration).\n"
                "- Whether 5.3's 'Direction of the errors' paragraph interprets more than a validation chapter should.\n"
                "- Whether the tests named without a citation (Tukey, Cochran's Q, the exact interval) need bib entries.")
sys.exit(r.finish())
